[package]
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]
edition = "2018"
name = "tracy"
version = "0.1.0"

[dependencies]
lazy_static = "1.4.0"

[dev-dependencies]
cucumber_rust = {version = "0.8.2", features = ["macros"]}
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}

[[test]]
harness = false
name = "ch01"

[[test]]
harness = false
name = "ch02"

[[test]]
harness = false
name = "ch03"

[[test]]
harness = false
name = "ch04"

[[test]]
harness = false
name = "ch05"

[[test]]
harness = false
name = "ch06"
