[package]
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]
edition = "2018"
name = "tracy"
version = "0.1.0"

[dependencies]
itertools = "0.10.0"

[dev-dependencies]
criterion = "0.3.4"

[[bench]]
harness = false
name = "perf"
